"""user authentication

Revision ID: ebd33af7ee16
Revises: 6e3dd771ad0c
Create Date: 2026-07-15 12:22:08.890517
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ebd33af7ee16'
down_revision: Union[str, None] = '6e3dd771ad0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('is_admin', sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
